export const horseNames = [
  'Sugarhoof',
  'Cupcake Dash',
  'Twinkle Trot',
  'Snickersnack',
  'Muffin Mane',
  'Peachy Keen',
  'Bubblegallop',
  'Fluffy Boots',
  'Cherry Canter',
  'Taffy Twirl',
  'Sprinkle Sparkle',
  'Giggle Gait',
  'Daisy Dancer',
  'Toffee Tail',
  'Nibble Nuzzle',
  'Honey Hooves',
  'Fizzy Flicka',
  'Coconut Clipclop',
  'Blueberry Blitz',
  'Pudding Pop',
  'Marshmallow Skip',
  'Lilac Leap',
  'Pumpkin Puff',
  'Doodle Trot',
  'Cuddlesnort',
  'Mochi Mane',
  'Caramel Crunch',
  'Snuggle Snout',
  'Whimsy Whinny',
  'Cookie Gallop',
  'Lollipop Loop',
  'Moonpie Mayhem',
  'Petal Prance',
  'Zigzag Zoomie',
  'Sunbeam Swoosh',
  'Jellybean Jive',
  'Flutterfluff',
  'Pixie Canter',
  'Boop the Neigh',
  'Waffles McTrot',
]
